### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by aigeek** [gaop-0561/PicBed4MWeb#1]
➜  PicBed4MWeb git:(master) ✗ node index.js
/Users/kk/Development/open_source/tools/PicBed4MWeb/helper.js:21
async function getImgUrl(file){
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kk/Development/open_source/tools/PicBed4MWeb/index.js:4:19)
    at Module._compile (module.js:556:32)

**Comment by gaop-0561** [comment]
Put your Github token into config.json，https://github.com/settings/tokens
